all: main test

main:
	g++ main.cpp BigNum.cpp BigNum.h multiply.s -m32 -O3 -o OiAK_Potegowanie
test:
	g++ main_test.cpp BigNum.cpp BigNum.h multiply.s -m32 -O3 -o OiAK_Potegowanie_TEST
clean:
	rm OiAK_Mnozenie
